from __future__ import annotations

import csv
import json
from pathlib import Path
from textwrap import fill
from typing import Any

from tatm.io import write_json


def _percent(value: float) -> str:
    return f"{100 * value:.2f}%"


def _table(headers: list[str], rows: list[list[Any]]) -> str:
    def cell(value: Any) -> str:
        return str(value).replace("|", "\\|").replace("\n", " ")

    lines = [
        "| " + " | ".join(cell(header) for header in headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(cell(value) for value in row) + " |")
    return "\n".join(lines)


def _write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    fieldnames = list(rows[0])
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=fieldnames,
            lineterminator="\n",
        )
        writer.writeheader()
        writer.writerows(rows)


def write_dataset_inventory(
    path: Path,
    metadata: dict[str, Any],
    summary: dict[str, Any],
) -> None:
    inventory = summary["inventory"]
    token_dist = inventory["schema_token_distribution"]
    issue_rows = [
        [issue, count]
        for issue, count in inventory["schema_issue_counts"].items()
    ]
    source_rows = [
        [source, count] for source, count in inventory["tool_sources"].items()
    ]
    source_token_rows = [
        [
            source,
            values["median"],
            values["p95"],
            values["max"],
            values["mean"],
        ]
        for source, values in inventory[
            "source_schema_token_distribution"
        ].items()
    ]
    domain_rows = [
        [domain, count]
        for domain, count in list(inventory["top_tool_domains"].items())[:15]
    ]
    longest_rows = [
        [
            row["name"],
            row["source"],
            row["domain"],
            row["schema_tokens"],
        ]
        for row in inventory["longest_tools"][:10]
    ]
    text = f"""# Dataset inventory and schema report

## Scope

This report is generated by `scripts/run_pipeline.py`. It normalizes all public
ToolRet corpus shards and queries plus a static BFCL V4 subset: simple Python,
multiple, parallel, parallel-multiple, and irrelevance.

Public sources:

- [ToolRet paper](https://arxiv.org/abs/2503.01763),
  [tool corpus](https://huggingface.co/datasets/mangopy/ToolRet-Tools), and
  [query corpus](https://huggingface.co/datasets/mangopy/ToolRet-Queries);
- [BFCL repository and format documentation](https://github.com/ShishirPatil/gorilla/tree/main/berkeley-function-call-leaderboard).

ToolRet labels are relevance judgments. BFCL `function` arrays are the tools
exposed to a task, not necessarily the gold functions called. Neither source is
a chronological production trace.

## Inventory

{_table(
    ["Dataset", "Canonical tools", "Tasks", "Evidence"],
    [
        [
            "ToolRet",
            metadata["toolret"]["tools"],
            metadata["toolret"]["tasks"],
            "gold relevance",
        ],
        [
            "BFCL subset",
            metadata["bfcl"]["tools"],
            metadata["bfcl"]["tasks"],
            "exposed menu",
        ],
        [
            "Combined",
            metadata["combined"]["tools"],
            metadata["combined"]["tasks"],
            "mixed; analyzed separately",
        ],
    ],
)}

ToolRet has {metadata["toolret"]["missing_label_references"]} label references
that do not resolve to the downloaded corpus and
{metadata["toolret"]["empty_label_tasks"]} tasks with no parsed labels.

## Canonical serialization

Each normalized tool is serialized deterministically as:

```json
{{"function":{{"description":"...","name":"...","parameters":{{...}}}},"type":"function"}}
```

Object keys are sorted, whitespace is removed, UTF-8 text is preserved, and
parameter dictionaries are normalized to JSON Schema object form. Counts use
`{summary["tokenizer"]}` without a chat-template wrapper.

## Tool sources

{_table(["Source", "Tools"], source_rows)}

## Canonical schema-token length

{_table(
    ["Count", "Min", "Median", "P90", "P95", "P99", "Max", "Mean"],
    [[
        token_dist["count"],
        token_dist["min"],
        token_dist["median"],
        token_dist["p90"],
        token_dist["p95"],
        token_dist["p99"],
        token_dist["max"],
        token_dist["mean"],
    ]],
)}

### Length by source

{_table(
    ["Source", "Median", "P95", "Max", "Mean"],
    source_token_rows,
)}

### Ten longest canonical schemas

{_table(
    ["Tool", "Source", "Domain", "Schema tokens"],
    longest_rows,
)}

## Schema-quality flags

Flags are descriptive normalization diagnostics, not proof that a benchmark
record is unusable. For example, a no-argument function legitimately has an
empty parameter object.

{_table(["Issue", "Tools"], issue_rows)}

Tools with at least one flag: {inventory["tools_with_any_issue"]} of
{inventory["tools"]}.

## Largest inferred domains

{_table(["Domain", "Tools"], domain_rows)}

## Format observations

- ToolRet corpus files are Parquet with `id` and a heterogeneous JSON-encoded
  `documentation` field. Query Parquet files contain `id`, query/instruction
  text, JSON-encoded relevance `labels`, and category metadata.
- BFCL files use JSON Lines despite the `.json` extension. Each task contains a
  conversation-like `question` and one or more inline function definitions.
- ToolRet code tools often use non-OpenAI fields such as `functionality`,
  `api_call`, `api_arguments`, and `example_code`; the normalizer records
  missing fields instead of silently inventing rich schemas.
- BFCL function definitions are merged by canonical schema hash so repeated
  identical definitions share an identity.

## Limitations

Token counts exclude model-specific chat-template wrappers and separators, so
cluster requests must re-tokenize the complete rendered prompt. Public benchmark
frequency must not be presented as production popularity. BFCL menu exposure
must not be presented as successful-call frequency.
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def write_access_patterns(path: Path, summary: dict[str, Any]) -> None:
    sections: list[str] = [
        "# Tool-access, replay, and trie analysis",
        "",
        "This report keeps ToolRet gold relevance and BFCL menu exposure in "
        "separate partitions. Ordered adjacency is only an order proxy; neither "
        "dataset provides a natural production execution trace.",
    ]
    for partition_name, partition in summary["partitions"].items():
        tool_count = partition["task_tool_count"]
        token_count = partition["task_schema_tokens"]
        top_tool_rows = [
            [
                row["name"],
                row["occurrences"],
                row["schema_tokens"],
                row["weighted_tokens"],
            ]
            for row in partition["top_tools"][:10]
        ]
        empirical_rows = [
            [
                row["ordering"],
                row["trie_nodes"],
                _percent(row["node_compression_ratio"]),
                row["cacheable_block_tokens"],
                _percent(row["estimated_block_reuse_ratio"]),
            ]
            for row in partition["ordering_results"]
            if row["replay"] == "empirical"
        ]
        locality_rows = [
            [
                row["replay"],
                _percent(row["same_domain_ratio"]),
                _percent(row["shared_tool_ratio"]),
                f'{row["mean_tool_jaccard"]:.4f}',
            ]
            for row in partition["locality"]
        ]
        # One ordering is enough to show the locality effect; sweeping every
        # ordering across every capacity would bury it in rows.
        capacity_rows = [
            [
                _percent(row["capacity_fraction"]),
                row["replay"],
                _percent(row["estimated_block_reuse_ratio"]),
                f'{row["evictions"]:,}',
            ]
            for row in partition["capacity_results"]
            if row["ordering"] == "frequency"
        ]
        pair_rows = [
            [
                " + ".join(row["tool_names"]),
                row["count"],
            ]
            for row in partition["top_pairs"][:10]
        ]
        triple_rows = [
            [
                " + ".join(row["tool_names"]),
                row["count"],
            ]
            for row in partition["top_triples"][:10]
        ]
        adjacency_rows = [
            [
                f'{row["tool_names"][0]} → {row["tool_names"][1]}',
                row["count"],
                _percent(row["p_next_given_current"]),
            ]
            for row in partition["top_ordered_adjacency_proxy"][:10]
        ]
        replay_best_rows: list[list[Any]] = []
        for replay in ("empirical", "uniform", "skewed", "session_bursty"):
            candidates = [
                row
                for row in partition["ordering_results"]
                if row["replay"] == replay
            ]
            best = max(
                candidates,
                key=lambda row: (
                    row["estimated_block_reuse_ratio"],
                    row["node_compression_ratio"],
                ),
                default=None,
            )
            if best:
                replay_best_rows.append(
                    [
                        replay,
                        best["ordering"],
                        _percent(best["estimated_block_reuse_ratio"]),
                        _percent(best["node_compression_ratio"]),
                    ]
                )

        sections.extend(
            [
                "",
                f"## {partition_name}",
                "",
                _table(
                    [
                        "Tasks",
                        "Unique observed tools",
                        "Tools/task median",
                        "Tools/task P95",
                        "Schema tokens/task median",
                        "Schema tokens/task P95",
                    ],
                    [[
                        partition["tasks"],
                        partition["unique_observed_tools"],
                        tool_count["median"],
                        tool_count["p95"],
                        token_count["median"],
                        token_count["p95"],
                    ]],
                ),
                "",
                "### Highest benchmark support",
                "",
                _table(
                    ["Tool", "Occurrences", "Schema tokens", "Weighted tokens"],
                    top_tool_rows,
                ),
                "",
                "### Co-occurrence and ordered-adjacency proxies",
                "",
                "Co-occurrence is an unordered same-task statistic. Adjacency "
                "uses dataset label/menu order and is not a measured execution "
                "transition.",
                "",
                _table(["Top pair", "Tasks"], pair_rows),
                "",
                _table(["Top triple", "Tasks"], triple_rows),
                "",
                _table(
                    ["Ordered adjacency", "Count", "P(next | current)"],
                    adjacency_rows,
                ),
                "",
                "### Empirical-order trie comparison",
                "",
                _table(
                    [
                        "Ordering",
                        "Trie nodes",
                        "Node compression",
                        "Block-cacheable tokens",
                        "Estimated token reuse",
                    ],
                    empirical_rows,
                ),
                "",
                "FP-tree-style global ordering is descending global support, so "
                "it is intentionally identical to the frequency baseline in this "
                "first implementation. Future conditional FP-tree mining should "
                "be evaluated as a distinct extension.",
                "",
                "### Replay locality",
                "",
                _table(
                    [
                        "Replay",
                        "Same-domain adjacency",
                        "Shared-tool adjacency",
                        "Mean tool Jaccard",
                    ],
                    locality_rows,
                ),
                "",
                "### Best ordering per replay (analytical estimate)",
                "",
                _table(
                    [
                        "Replay",
                        "Ordering",
                        "Estimated token reuse",
                        "Node compression",
                    ],
                    replay_best_rows,
                ),
                "",
                "The three tables above assume unbounded retention. Under that "
                "assumption trie reuse depends only on the multiset of requests "
                "and not on their order, so `session_bursty` — a permutation of "
                "`empirical` — is identical to it **by construction**, and the "
                "`uniform`/`skewed` differences come from resampling with "
                "replacement rather than from locality. Request order can only "
                "matter once capacity forces eviction, so the locality question "
                "is answered by the next table, not by these.",
                "",
                "### Reuse under a finite cache (frequency ordering)",
                "",
                "Capacity is a fraction of this partition's distinct-tool token "
                f'working set ({partition["working_set_tokens"]:,} tokens), '
                "evicted leaf-first by least-recently-used.",
                "",
                _table(
                    [
                        "Capacity",
                        "Replay",
                        "Estimated token reuse",
                        "Evictions",
                    ],
                    capacity_rows,
                ),
                "",
                f"Pair/triple calculations skipped "
                f'{partition["cooccurrence_tasks_skipped_over_25_tools"]["pairs"]}'
                " tasks with more than 25 exposed tools to avoid combinatorial "
                "distortion.",
            ]
        )

    sections.extend(
        [
            "",
            "## Interpretation boundary",
            "",
            "The cache result is an analytical tool-unit trie estimate. It rounds "
            "shared canonical tool tokens down to 16-token blocks. It excludes "
            "constant system/user prefixes, chat-template separators, GPU "
            "pressure, and scheduler effects, and it counts reuse at tool "
            "boundaries while real block boundaries fall wherever the rendered "
            "prompt puts them. It is therefore a partial proxy, not a guaranteed "
            "upper bound or a latency prediction: omitted shared prefixes can "
            "raise measured reuse, while block misalignment and eviction can "
            "lower it. The finite-cache tables model eviction; the unbounded "
            "tables do not. Measured engine cache hits are required before any "
            "latency claim.",
            "",
            "A useful positive signal is ordering-dependent block reuse on "
            "multi-tool workloads, especially under bursty replay. A negative or "
            "flat ToolRet result is also expected when most relevance sets contain "
            "one tool; reordering cannot improve a one-item sequence.",
            "",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(sections), encoding="utf-8")


def load_probe_results(results_dir: Path) -> dict[str, Any] | None:
    """Load the Task B probe outputs if they have been produced on a GPU.

    Reports are generated by the pipeline, so measured results should normally
    be read back here rather than hand-written into markdown. If cluster-only
    raw files are absent, ``write_initial_findings`` preserves the already
    committed measured section while regenerating the surrounding analysis.
    """
    def read(name: str) -> dict[str, Any] | None:
        path = results_dir / name
        if not path.exists():
            return None
        return json.loads(path.read_text(encoding="utf-8"))

    enabled = read("cache-enabled.json")
    if enabled is not None and enabled.get("format_version", 1) < 2:
        enabled = None  # single-trial format has no intervals; treat as absent

    validations = [
        json.loads(path.read_text(encoding="utf-8"))
        for path in sorted(results_dir.glob("validate-*.json"))
    ]
    quality_06b = {
        "alphabetical": read("bfcl-quality-alphabetical-score.json"),
        "frequency": read("bfcl-quality-frequency-score.json"),
    }
    quality_8b = {
        "alphabetical": read("bfcl-quality-alphabetical-8b-score.json"),
        "frequency": read("bfcl-quality-frequency-8b-score.json"),
    }
    locality_replays = [
        json.loads(path.read_text(encoding="utf-8"))
        for path in sorted(results_dir.glob("locality-replay-*.json"))
    ]
    bundle = {
        "enabled": enabled,
        "disabled": read("cache-disabled.json"),
        "sweep_enabled": read("prefill-sweep-enabled.json"),
        "sweep_disabled": read("prefill-sweep-disabled.json"),
        "validations": validations,
        "quality_06b": quality_06b if any(quality_06b.values()) else None,
        "quality_8b": quality_8b if any(quality_8b.values()) else None,
        "locality_replays": locality_replays,
    }
    return bundle if any(bundle.values()) else None


_PROBE_SCENARIOS = (
    ("original_cold", "Cold prompt"),
    ("original_identical", "Identical prompt reuse"),
    ("changed_second_tool", "Changed second tool"),
    ("reordered_first_two", "Reordered first two tools"),
    ("original_restored", "Original restored"),
)


def _sweep_section(probe: dict[str, Any] | None) -> str:
    """Where prefix caching starts to pay, measured against a control."""
    if probe is None or probe.get("sweep_enabled") is None:
        return ""
    enabled = probe["sweep_enabled"]
    disabled = probe.get("sweep_disabled")
    off_by_size = {}
    if disabled is not None:
        off_by_size = {row["menu_tools"]: row for row in disabled["results"]}

    rows = []
    crossover = None
    for row in enabled["results"]:
        warm = row["warm_ttft_seconds"]["mean"]
        cold = row["cold_ttft_seconds"]["mean"]
        off_row = off_by_size.get(row["menu_tools"])
        off_warm = off_row["warm_ttft_seconds"]["mean"] if off_row else None
        speedup = f"{off_warm / warm:.1f}x" if off_warm and warm else "—"
        if off_warm and off_warm / warm >= 1.2 and crossover is None:
            crossover = row["menu_tools"]
        rows.append(
            [
                row["menu_tools"],
                f'{row["prompt_tokens"]:,}',
                f"{cold * 1000:.1f}",
                f"{warm * 1000:.1f}",
                f"{off_warm * 1000:.1f}" if off_warm else "—",
                speedup,
            ]
        )

    crossover_text = (
        f"Prefix caching first produces a material gain at **{crossover} tools** "
        "and grows steeply from there."
        if crossover
        else "No menu size showed a material cache-on/cache-off gap."
    )
    return "\n".join(
        [
            "## Prefill cost and the measurement floor",
            "",
            "Menus are one gold tool padded with distractors from a fixed global "
            "catalog. Cold is measured after a prefix-cache reset; warm is an "
            f'identical repeat. {enabled["repeats"]} trials per point.',
            "",
            _table(
                [
                    "Menu tools",
                    "Prompt tokens",
                    "Cold TTFT on (ms)",
                    "Warm TTFT on (ms)",
                    "Warm TTFT off (ms)",
                    "Speedup",
                ],
                rows,
            ),
            "",
            crossover_text,
            "",
            "The cache-disabled control shows cold and warm within noise of each "
            "other at every size, so the gap above is prefix caching and not a "
            "warmup artifact. Note that within-run cold-vs-warm separation alone "
            "is not sufficient evidence: the control also 'separates' at one tool, "
            "where no cache exists. The cache-on/cache-off comparison is the "
            "trustworthy one.",
            "",
            "This supersedes the earlier reading that prefix reuse buys nothing. "
            "It buys nothing *at 303 tokens*, which is simply below the floor.",
            "",
        ]
    )


def _validation_section(probe: dict[str, Any] | None) -> str:
    """Analytical trie estimate versus what vLLM actually cached."""
    if probe is None or not probe.get("validations"):
        return ""
    rows = []
    for run in probe["validations"]:
        predicted = run["predicted"]
        measured = run["measured"]
        rows.append(
            [
                run["run_label"].replace("validate-", ""),
                f'{predicted["cacheable_block_tokens"]:,}',
                f'{measured["cached_prompt_tokens"]:,.0f}',
                f'{run["measured_over_predicted_ratio"]:.2f}x'
                if run.get("measured_over_predicted_ratio")
                else "—",
                _percent(predicted["estimated_block_reuse_ratio"]),
                _percent(measured["measured_reuse_ratio"]),
            ]
        )
    return "\n".join(
        [
            "## Analytical estimate versus measured cache hits",
            "",
            _table(
                [
                    "Workload",
                    "Predicted cacheable",
                    "Measured cached",
                    "Measured/predicted",
                    "Predicted reuse",
                    "Measured reuse",
                ],
                rows,
            ),
            "",
            "The tool-unit model under-predicts rather than over-predicts. It "
            "ignores the chat template and system preamble, which are identical "
            "across requests and are themselves cached, and that outweighs the "
            "partial blocks it loses at tool boundaries.",
            "",
            "The ordering comparison inverts the gold-only recommendation. On "
            "padded menus, ordering by benchmark support puts the *task-specific* "
            "tools first and pushes the shared catalog behind them, destroying the "
            "common prefix. A stable global order that ignores task-specificity "
            "keeps the shared catalog in front. Frequency ordering is the right "
            "choice only when the whole menu is task-specific, which is not what a "
            "connected tool catalog looks like.",
            "",
        ]
    )


def _quality_section(probe: dict[str, Any] | None) -> str:
    """Function-call quality under ordering, at whichever model sizes were run."""
    if probe is None:
        return ""
    quality_06b = probe.get("quality_06b")
    quality_8b = probe.get("quality_8b")
    if not quality_06b and not quality_8b:
        return ""

    def rows_for(bundle: dict[str, Any] | None) -> list[list[Any]]:
        rows = []
        for ordering in ("alphabetical", "frequency"):
            score = (bundle or {}).get(ordering)
            if score is None:
                continue
            overall = score["overall"]
            rows.append(
                [
                    ordering,
                    _percent(overall["function_name_accuracy"] or 0),
                    _percent(overall["full_accuracy"] or 0),
                    _percent(overall["no_tool_accuracy"] or 0),
                ]
            )
        return rows

    sections = [
        "## Does the winning ordering preserve function-call quality?",
        "",
        "100 BFCL tasks (20 per category, 64-tool menus), scored against BFCL "
        "`possible_answer` ground truth. Alphabetical is the ordering measured "
        "strongest for cache reuse; frequency is the comparison Task D's "
        "analytical model originally recommended.",
        "",
    ]
    rows_06b = rows_for(quality_06b)
    if rows_06b:
        sections.extend(
            [
                "`Qwen/Qwen3-0.6B`:",
                "",
                _table(
                    [
                        "Ordering",
                        "Function-name accuracy",
                        "Full accuracy",
                        "No-tool accuracy",
                    ],
                    rows_06b,
                ),
                "",
            ]
        )
    rows_8b = rows_for(quality_8b)
    if rows_8b:
        sections.extend(
            [
                "`Qwen/Qwen3-8B`, identical workload:",
                "",
                _table(
                    [
                        "Ordering",
                        "Function-name accuracy",
                        "Full accuracy",
                        "No-tool accuracy",
                    ],
                    rows_8b,
                ),
                "",
            ]
        )
    if rows_06b and rows_8b:
        sections.append(
            "The name/full-accuracy gap that looked real at 0.6B is not present "
            "at 8B — both orderings score identically there. Checking a "
            "counterintuitive small-model result against a second model size "
            "found that most of the apparent quality tradeoff was a small-model "
            "artefact; only a smaller no-tool-accuracy gap favouring alphabetical "
            "survives at both scales. One run per condition, no repeats; read as "
            "directional rather than final."
        )
    else:
        sections.append(
            "One run per condition, no repeats or confidence intervals, and only "
            "two of six orderings scored; read as directional rather than final."
        )
    sections.append("")
    return "\n".join(sections)


def _locality_replay_section(probe: dict[str, Any] | None) -> str:
    """Whether request order changes reuse under real GPU cache eviction."""
    if probe is None or not probe.get("locality_replays"):
        return ""
    rows = []
    note = None
    has_legacy = False
    for run in probe["locality_replays"]:
        legacy = int(run.get("format_version", 1)) < 2
        has_legacy |= legacy
        capacity = run.get("cache_capacity_tokens")
        for name, condition in run.get("conditions", {}).items():
            predicted = condition.get("predicted", {})
            volume = condition.get("total_prompt_tokens", 0)
            volume_type = (
                "canonical tool tokens" if legacy else "rendered prompt tokens"
            )
            rows.append(
                [
                    name,
                    f"{volume:,}",
                    volume_type,
                    f'{condition.get("measured_cached_tokens", 0):,.0f}',
                    _percent(condition["measured_reuse_ratio"]),
                    _percent(predicted.get("estimated_block_reuse_ratio", 0)),
                    f'{predicted.get("evictions", 0):,}',
                ]
            )
        if note is None and capacity:
            total = next(iter(run.get("conditions", {}).values()), {}).get(
                "total_prompt_tokens", 0
            )
            note = (
                f"Recorded {volume_type} volume ({total:,}) versus nominal "
                "cache capacity "
                f"({capacity:,} tokens) for this run."
            )
    if not rows:
        return ""
    return "\n".join(
        [
            "## Does request order matter on the live GPU cache?",
            "",
            "Every other GPU experiment above resets the prefix cache before each "
            "trial, which is repeatable but erases the cross-request dependency "
            "locality is actually about. This instead runs one continuous session "
            "per replay condition — a single reset, then every request in "
            "sequence — comparing `empirical` against `session_bursty`, the one "
            "replay pair that is a strict permutation of the same task multiset.",
            "",
            _table(
                [
                    "Replay",
                    "Recorded token volume",
                    "Volume type",
                    "Measured cached tokens",
                    "Cached / recorded volume",
                    "Predicted reuse (bounded trie)",
                    "Predicted evictions",
                ],
                rows,
            ),
            "",
            note or "",
            "",
            (
                "Legacy format-v1 runs mislabeled canonical tool-token volume "
                "as full prompt tokens, so their displayed cached/volume value "
                "is not a standard rendered-prompt cache-hit ratio. Their "
                "measured cached-token totals remain usable for a matched "
                "between-order comparison, but they did not sample occupancy "
                "and cannot directly prove eviction. Re-run with format v2 for "
                "the corrected denominator and measured pressure."
                if has_legacy
                else "Format-v2 runs use rendered prompt tokens, reconcile them "
                "with the engine query counter, and include sampled KV occupancy. "
                "Only runs that reached their predeclared pressure threshold "
                "should support an eviction-pressure claim."
            ),
            "",
        ]
    )


def _probe_section(probe: dict[str, Any] | None) -> str:
    if probe is None or probe.get("enabled") is None:
        return (
            "## Prefix-cache sanity status\n\n"
            "Not yet measured. Run `scripts/vllm_prefix_cache_probe.py` on a "
            "CUDA GPU as described in `cluster/README.md`; no synthetic number "
            "is substituted here.\n"
        )

    enabled = probe["enabled"]
    disabled = probe.get("disabled")
    config = enabled.get("server_cache_config", {})
    rows = []
    for key, label in _PROBE_SCENARIOS:
        summary_row = enabled["summary"][key]
        cached = summary_row["cached_prompt_tokens"]["mean"]
        prompt_tokens = summary_row["prompt_tokens"]
        ttft = summary_row["ttft_seconds"]
        cell = f'{ttft["mean"] * 1000:.1f} ± {ttft.get("ci95_half_width", 0) * 1000:.1f}'
        off_cell = "—"
        if disabled is not None:
            off = disabled["summary"][key]["ttft_seconds"]
            off_cell = (
                f'{off["mean"] * 1000:.1f} ± '
                f'{off.get("ci95_half_width", 0) * 1000:.1f}'
            )
        rows.append(
            [
                label,
                f'{cached:.0f} / {"/".join(str(v) for v in prompt_tokens)}',
                _percent(summary_row["reuse_fraction"]),
                cell,
                off_cell,
            ]
        )

    control_note = (
        "No cache-disabled control has been run, so output equality is "
        "unverified."
    )
    if disabled is not None:
        control_flag = disabled.get("server_cache_config", {}).get(
            "enable_prefix_caching"
        )
        max_cached = max(
            row["cached_prompt_tokens"]["max"]
            for row in disabled["summary"].values()
        )
        if control_flag is False and max_cached == 0:
            control_note = (
                "The control served `enable_prefix_caching=False` and reported "
                "0 cached tokens in every scenario, so the cache-on/cache-off "
                "output comparison is meaningful."
            )
        else:
            control_note = (
                "**The control is invalid**: it served "
                f"`enable_prefix_caching={control_flag}` and reported up to "
                f"{max_cached:.0f} cached tokens. Omitting "
                "`--enable-prefix-caching` does not disable the feature in "
                "vLLM V1; restart with `--no-enable-prefix-caching`."
            )

    return "\n".join(
        [
            "## Prefix-cache sanity results",
            "",
            f'Measured on {enabled["model"]}, block size '
            f'{config.get("block_size")}, {config.get("num_gpu_blocks")} GPU '
            f'blocks, {enabled["repeats"]} trials per scenario with the prefix '
            "cache reset before each trial. Intervals are 95% Student-t "
            "half-widths.",
            "",
            _table(
                [
                    "Check",
                    "Cached / prompt tokens",
                    "Reuse",
                    "TTFT on (ms)",
                    "TTFT off (ms)",
                ],
                rows,
            ),
            "",
            control_note,
            "",
        ]
    )


def _initial_brief_closure_section(report_path: Path) -> str:
    """Render the tracked retrieved-menu GPU evidence into the initial report."""
    handover_dir = (
        report_path.parent
        / "initial-brief-closure"
        / "20260805-222246-gpu-executor"
    )
    summary_paths = {
        menu_size: handover_dir / f"retrieved-k{menu_size}-summary.json"
        for menu_size in (4, 16, 64, 128)
    }
    audit_path = handover_dir / "audit-k64-validation-summary.json"
    pressure_path = handover_dir / "pressure-bfcl-k64-summary.json"
    accepted_pressure_path = (
        report_path.parent
        / "initial-brief-pressure-rerun"
        / "20260807-005414"
        / "pressure-summary.json"
    )
    equivalence_path = (
        report_path.parent
        / "initial-brief-pressure-rerun"
        / "ordering-equivalence.json"
    )
    retrieval_path = report_path.parent / "retrieval-bm25-sweep.json"
    required_paths = [
        *summary_paths.values(),
        audit_path,
        pressure_path,
        accepted_pressure_path,
        equivalence_path,
        retrieval_path,
    ]
    if not all(path.exists() for path in required_paths):
        return ""

    summaries = {
        menu_size: json.loads(path.read_text(encoding="utf-8"))
        for menu_size, path in summary_paths.items()
    }
    retrieval = json.loads(retrieval_path.read_text(encoding="utf-8"))
    audit = json.loads(audit_path.read_text(encoding="utf-8"))
    pressure = json.loads(pressure_path.read_text(encoding="utf-8"))
    accepted_pressure = json.loads(
        accepted_pressure_path.read_text(encoding="utf-8")
    )
    equivalence = json.loads(equivalence_path.read_text(encoding="utf-8"))

    display_names = {
        "original": "Original fallback",
        "alphabetical": "Alphabetical",
        "random": "Random seed 42",
        "frequency": "Frequency",
        "schema_cost_weighted": "Schema-cost weighted",
        "fp_tree_global": "FP-tree global",
        "tooltrie_v0": "ToolTrie-v0",
    }
    condition_ids = tuple(display_names)
    reuse_rows = []
    systems_rows = []
    for menu_size, summary in summaries.items():
        conditions = summary["conditions"]
        reuse_rows.append(
            [menu_size]
            + [
                _percent(
                    conditions[condition]["measurements"]["cached_ratio"]["mean"]
                )
                for condition in condition_ids
            ]
        )
        fallback = conditions["original"]
        tooltrie = conditions["tooltrie_v0"]
        fallback_reuse = fallback["measurements"]["cached_ratio"]["mean"]
        tooltrie_reuse = tooltrie["measurements"]["cached_ratio"]["mean"]
        best_static = max(
            conditions[condition]["measurements"]["cached_ratio"]["mean"]
            for condition in condition_ids[:-1]
        )
        requests = fallback["requests"]
        systems_rows.append(
            [
                menu_size,
                f'{fallback["prompt_tokens"] / requests:,.0f}',
                _percent(fallback_reuse),
                _percent(best_static),
                _percent(tooltrie_reuse),
                f"{100 * (tooltrie_reuse - fallback_reuse):+.2f} pp",
                f'{1000 * fallback["measurements"]["ttft_seconds"]["mean"] / requests:.1f}',
                f'{1000 * tooltrie["measurements"]["ttft_seconds"]["mean"] / requests:.1f}',
            ]
        )

    retrieval_rows = [
        [
            row["k"],
            _percent(row["mean_recall"]),
            _percent(row["hit_rate"]),
            f'{row["mean_reciprocal_rank"]:.4f}',
        ]
        for row in retrieval["retrieval_curve"]
    ]
    k64 = summaries[64]["conditions"]
    alpha_partial = k64["alphabetical"]["direct_reuse_buckets"]["partial_all"]
    trie_partial = k64["tooltrie_v0"]["direct_reuse_buckets"]["partial_all"]
    pressure_runs = pressure["all_regime_runs"]
    pressure_passes = sum(
        result["requirement_met"]
        for regimes in pressure["orderings"].values()
        for result in regimes.values()
    )
    pressure_peaks = [
        result["peak_kv_usage_fraction"]
        for regimes in pressure["orderings"].values()
        for result in regimes.values()
    ]
    accepted_peaks = [
        result["peak_kv_usage_fraction"]
        for regimes in accepted_pressure["orderings"].values()
        for result in regimes.values()
    ]
    accepted_evictions = [
        result["eviction_events_sampled"]
        for regimes in accepted_pressure["orderings"].values()
        for result in regimes.values()
    ]
    pressure_groups = (
        ("Original", "original"),
        ("Alphabetical", "alphabetical"),
        ("Random seed 42", "random"),
        ("Frequency = schema-cost = FP-tree", "frequency"),
    )
    pressure_rows = []
    for label, ordering in pressure_groups:
        regimes = accepted_pressure["orderings"][ordering]
        evictions = [row["eviction_events_sampled"] for row in regimes.values()]
        pressure_rows.append(
            [
                label,
                _percent(regimes["empirical"]["measured_reuse_ratio"]),
                _percent(regimes["uniform"]["measured_reuse_ratio"]),
                _percent(regimes["skewed"]["measured_reuse_ratio"]),
                _percent(regimes["session_bursty"]["measured_reuse_ratio"]),
                f"{min(evictions):,.0f}-{max(evictions):,.0f}",
            ]
        )

    def paragraph(value: str) -> str:
        return fill(
            value,
            width=88,
            break_long_words=False,
            break_on_hyphens=False,
        )

    return "\n".join(
        [
            "## Retrieved-menu GPU arm",
            "",
            paragraph(
                "A deterministic BM25 baseline selected each ToolRet menu "
                "without reading gold IDs; gold labels were used only for the "
                "separate retrieval evaluation. All ordering conditions used "
                "the same selected tool membership and request sequence. Each "
                "cache result below is three clean 200-request trials on "
                "Qwen3-0.6B/vLLM."
            ),
            "",
            _table(["Menu k", "Macro recall", "Hit rate", "MRR"], retrieval_rows),
            "",
            _table(
                ["k", *display_names.values()],
                reuse_rows,
            ),
            "",
            _table(
                [
                    "k",
                    "Prompt tokens/query",
                    "Fallback reuse",
                    "Best static reuse",
                    "ToolTrie reuse",
                    "ToolTrie - fallback",
                    "Fallback TTFT/query (ms)",
                    "ToolTrie TTFT/query (ms)",
                ],
                systems_rows,
            ),
            "",
            paragraph(
                "ToolTrie-v0 has the highest reuse at every retrieved menu "
                "size, but the absolute advantage over ordinary retrieval-rank "
                "text prefill is only 0.76-1.65 percentage points. Reuse falls "
                "as menus grow because independently retrieved sets share "
                "little exact rendered prefix. The three-trial TTFT intervals "
                "overlap and no paired-difference interval was predeclared, so "
                "these data do not establish a TTFT improvement."
            ),
            "",
            paragraph(
                "At k=64, both predeclared direct partial-reuse strata contain "
                "199 requests per trial (plus one cold request). Alphabetical "
                f'measured {100 * alpha_partial["cached_ratio"]["mean"]:.2f}% '
                "reuse and "
                f'{1000 * alpha_partial["mean_ttft_seconds"]["mean"]:.1f} ms '
                "TTFT; ToolTrie measured "
                f'{100 * trie_partial["cached_ratio"]["mean"]:.2f}% and '
                f'{1000 * trie_partial["mean_ttft_seconds"]["mean"]:.1f} ms. '
                "This is direct partial-reuse evidence, but the latency "
                "difference is too small to support a speed claim."
            ),
            "",
            "## Exact rendered-token and memory audit",
            "",
            paragraph(
                f'All {len(audit["conditions"])}/7 k64 rendered-prefix audits '
                f'are clean (`all_clean={str(audit["all_clean"]).lower()}`). '
                "The server rendered and tokenized the same chat-plus-tools "
                "payload used for completion; token counts and "
                "cached-plus-computed identities match for every request. "
                "Exact token IDs and block boundaries remain in the "
                "checksummed raw archive rather than Git."
            ),
            "",
            paragraph(
                f"The first pressure attempt produced {pressure_runs} clean, "
                f"reset regime-runs but accepted "
                f"{pressure_passes}/{pressure_runs}: sampled occupancy was only "
                f"{100 * min(pressure_peaks):.2f}-"
                f"{100 * max(pressure_peaks):.2f}% in a 190,896-token cache. "
                "The sequential client held one approximately 7k-token request "
                "resident; cumulative prompt volume is not residency. These "
                "runs are preserved and quarantined from pressure claims."
            ),
            "",
            paragraph(
                "The separately predeclared controlled-cache rerun is fully "
                f"accepted: {accepted_pressure['accepted_regime_runs']}/"
                f"{accepted_pressure['all_regime_runs']} regime-runs and "
                f"{accepted_pressure['checks_passed']}/"
                f"{accepted_pressure['checks_total']} checks passed at exactly "
                f"{accepted_pressure['expected_capacity_tokens']:,} tokens. "
                f"Peak occupancy was {100 * min(accepted_peaks):.2f}-"
                f"{100 * max(accepted_peaks):.2f}% against the unchanged 90% "
                f"threshold, with {min(accepted_evictions):,.0f}-"
                f"{max(accepted_evictions):,.0f} sampled evictions, zero "
                "preemptions, and one running/zero waiting requests throughout."
            ),
            "",
            _table(
                [
                    "Controlled-pressure ordering",
                    "Empirical reuse",
                    "Uniform reuse",
                    "Skewed reuse",
                    "Session-bursty reuse",
                    "Evictions",
                ],
                pressure_rows,
            ),
            "",
            paragraph(
                "This is a within-capacity stress comparison, not a latency or "
                "production-pressure result. Random seed 42 ranks first in all "
                "four regimes, but there is only one run per cell and one fixed "
                "random seed, with no uncertainty interval. That is insufficient "
                "to recommend random ordering. A deterministic reconstruction "
                f"finds {equivalence['distinct_orderings_per_regime']} distinct "
                "orders: frequency, schema-cost weighted, and FP-tree global "
                "emit exactly the same 200 sequences in every regime. They are "
                "one equivalence class here, not three independent policies."
            ),
            "",
        ]
    )


def write_initial_findings(
    path: Path,
    summary: dict[str, Any],
    probe: dict[str, Any] | None = None,
) -> None:
    token_dist = summary["inventory"]["schema_token_distribution"]
    toolret = summary["partitions"]["toolret_gold"]
    bfcl = summary["partitions"]["bfcl_exposed"]

    def empirical(partition: dict[str, Any], ordering: str) -> dict[str, Any]:
        return next(
            row
            for row in partition["ordering_results"]
            if row["replay"] == "empirical" and row["ordering"] == ordering
        )

    tr_original = empirical(toolret, "original")
    tr_weighted = empirical(toolret, "schema_cost_weighted")
    bf_original = empirical(bfcl, "original")
    bf_frequency = empirical(bfcl, "frequency")
    tr_gain = (
        tr_weighted["estimated_block_reuse_ratio"]
        - tr_original["estimated_block_reuse_ratio"]
    )
    bf_gain = (
        bf_frequency["estimated_block_reuse_ratio"]
        - bf_original["estimated_block_reuse_ratio"]
    )
    prefix_section = ""
    if probe is None or probe.get("enabled") is None:
        # Raw GPU replays are intentionally git-ignored and may exist only on
        # the cluster. A CPU-only regeneration must not erase a previously
        # committed measured section merely because those raw files are absent
        # on this machine. Preserve only the generated GPU block; the dataset
        # analysis and recommendation below are still regenerated normally.
        if path.exists():
            existing = path.read_text(encoding="utf-8")
            start = existing.find("## Prefix-cache sanity results")
            closure_start = existing.find("## Retrieved-menu GPU arm", start)
            recommendation_start = existing.find("## Recommendation", start)
            end = (
                closure_start
                if closure_start >= 0
                else recommendation_start
            )
            if start >= 0 and end > start:
                prefix_section = existing[start:end].strip()
    if not prefix_section:
        prefix_section = "\n".join(
            section
            for section in (
                _probe_section(probe),
                _sweep_section(probe),
                _validation_section(probe),
                _quality_section(probe),
                _locality_replay_section(probe),
            )
            if section
        )
    flagged = summary["inventory"]["tools_with_any_issue"]
    total_tools = summary["inventory"]["tools"]
    closure_section = _initial_brief_closure_section(path)

    text = f"""# Initial research findings and recommendation

## Result in one paragraph

The public workloads contain a measurable analytical prefix-locality signal,
but it is workload- and evidence-dependent. Across {total_tools:,} canonical
tools, median schema length is {token_dist["median"]:.0f} Qwen tokens and P95 is
{token_dist["p95"]:.0f}. ToolRet's median relevance set and BFCL's median
exposed menu both contain one tool, which limits what reordering can achieve on
many tasks. On empirical dataset order, schema-cost-weighted ordering raises the
ToolRet tool-prefix block-reuse estimate from
{_percent(tr_original["estimated_block_reuse_ratio"])} to
{_percent(tr_weighted["estimated_block_reuse_ratio"])} ({100 * tr_gain:.2f}
percentage points). Frequency ordering raises the BFCL menu estimate from
{_percent(bf_original["estimated_block_reuse_ratio"])} to
{_percent(bf_frequency["estimated_block_reuse_ratio"])} ({100 * bf_gain:.2f}
points). These are analytical estimates, not vLLM hit-rate or latency results.

## Evidence obtained locally

- ToolRet: {toolret["tasks"]:,} tasks, {toolret["unique_observed_tools"]:,}
  tools appearing in gold relevance labels, with every label resolved.
- BFCL subset: {bfcl["tasks"]:,} tasks and
  {bfcl["unique_observed_tools"]:,} distinct canonical functions appearing in
  exposed menus.
- Schema diagnostics flag {flagged:,}/{total_tools:,} tools. Most flags are
  empty parameter objects, which can be legitimate; malformed and missing-field
  counts are reported separately.
- Controlled support-skewed replay produces much more reuse than uniform or
  empirical access, but under unbounded retention that gap comes from
  resampling with replacement — repeated requests — not from locality. Only the
  finite-cache tables in `access-patterns.md` speak to request ordering.
- Classic FP-tree global order equals the frequency order in this baseline.
  Conditional pattern mining is still untested.

{prefix_section}

{closure_section}

## ContextPilot persistent-API confirmation

A pinned confirmation run used upstream commit
`1fa0a143fdeda344585666648ab2b30cb7fea77f`, the paper/default
`alpha=0.001`, one persistent `ContextPilot.reorder` index, stock vLLM, and the
same selected tool sets and request sequence. This is an **ordering-only
persistent-API adaptation**: workloads were planned before serving and no
eviction feedback, relevance annotations, or de-duplication were enabled. It is
not the full ContextPilot system.

On padded 64-tool menus it reaches 96.16% BFCL and 95.27% ToolRet reuse versus
87.19% and 83.58% for ToolTrie-v0. On BM25-retrieved ToolRet menus it also leads
ToolTrie at every measured size, but absolute reuse falls to 18.72%, 9.93%,
4.78%, and 1.99% at k=4/16/64/128. The 95–96% headline is therefore a
shared-menu positive-control result rather than a realistic retrieval result.

The Qwen3-8B quality replay gives the persistent arm +2.03 points on function
name, +2.03 on full call, and −5.00 on no-tool accuracy against alphabetical
on one fixed request sequence. A Qwen3-4B addendum reproduces the relevance
gain but gives exactly 0.00 points on no-tool. The current evidence supports a
model-sensitive quality frontier, not a universal safety penalty. See
`reports/contextpilot-confirmation/findings.md`.

## Recommendation

The retrieved-menu arm changes the recommendation. Alphabetical remains a
strong simple baseline on the padded shared-catalog workload, but it is not a
universal winner once menu membership comes from retrieval. ToolTrie-v0 gives
the highest reuse at all four retrieved menu sizes, yet its gain is small in
absolute terms and does not produce a resolved TTFT improvement. Retrieval
coverage and selected-set overlap are now the dominant bottlenecks: increasing
the BM25 menu from 4 to 128 raises macro recall from 41.71% to 67.54%, while
prompt cost grows about 25x and exact reuse falls.

Under the separately controlled 7,680-token pressure condition, fixed random
seed 42 measures the most reuse and the fewest evictions in all four regimes,
ahead of alphabetical. This ranking is capacity- and workload-specific, and a
single run per cell and random seed is not a policy result; run repeated seed
sweeps before treating it as more than a useful sensitivity finding.

The likely publishable refinement is not a generic "reorder context into a
trie" claim, because closely related cache-aware context ordering already
exists and the corrected ContextPilot persistent-API adaptation beats
ToolTrie-v0 on every padded and retrieved reuse cell measured. Both lose most
reuse on independently retrieved large menus, so retrieval overlap is the
stronger systems bottleneck. The historical static-refit arm and the persistent
arm must retain their exact labels; neither is full ContextPilot. The corrected
`alpha=0.001` static-refit confirmation and independent raw SGLang counter audit
remain GPU work.

Do not pursue arbitrary independent KV concatenation yet. Native exact APC
already converts the local token-reuse signal into a repeatable TTFT benefit
(10.6x at 200 tools). Phase 2 subsequently detected a fixed-sequence no-tool
regression among the measured high-reuse orders, so this report must not describe the optimization as
quality-preserving without that qualification. Keep ordinary selected-tool text
prefill as the explicit default fallback unless a predeclared cost model predicts
that reuse repays retrieval, context, decode, and safety costs.

## Initial-brief execution status

The explicit Tasks A-F and the stricter gap-closure manifest have been
substantively executed. Seven initial experimental questions are answered and
question 4 is partial: schema-token cost weighting was measured, but a policy
weighted by separately measured per-schema prefill time was not. The evidence includes
the ordinary fallback, BM25-retrieved menus, direct partial reuse, rendered-
token/block validation, and 24/24 accepted controlled-pressure regime-runs with
observed evictions. The original 0/24 runs remain preserved as valid low-
occupancy evidence rather than being rewritten.

This completes the planned initial experiment stage. The local analysis and
artifact-to-report audit are complete, but formal publication-grade closure
still needs the corrected `alpha=0.001` static-refit GPU cells, regeneration of
the GPU-side quality comparisons with sequence-state metadata, and independent
raw SGLang counter revalidation. Later §9 retained-tool or KV-composition
experiments remain extensions and must preserve the ordinary selected-tool text
fallback and the measured quality/safety frontier.
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def write_reports(
    report_dir: Path,
    metadata: dict[str, Any],
    summary: dict[str, Any],
    results_dir: Path | None = None,
) -> None:
    report_dir.mkdir(parents=True, exist_ok=True)
    write_json(report_dir / "analysis-summary.json", summary)
    write_dataset_inventory(
        report_dir / "dataset-inventory.md",
        metadata,
        summary,
    )
    write_access_patterns(report_dir / "access-patterns.md", summary)
    probe = load_probe_results(results_dir) if results_dir is not None else None
    write_initial_findings(report_dir / "initial-findings.md", summary, probe)

    table_dir = report_dir / "tables"
    issue_rows = [
        {"issue": issue, "tools": count}
        for issue, count in summary["inventory"]["schema_issue_counts"].items()
    ]
    _write_csv(table_dir / "schema-issues.csv", issue_rows)

    top_tool_rows: list[dict[str, Any]] = []
    pair_rows: list[dict[str, Any]] = []
    ordering_rows: list[dict[str, Any]] = []
    locality_rows: list[dict[str, Any]] = []
    for partition_name, partition in summary["partitions"].items():
        top_tool_rows.extend(
            {"partition": partition_name, **row}
            for row in partition["top_tools"]
        )
        pair_rows.extend(
            {
                "partition": partition_name,
                "tool_1": row["tool_names"][0],
                "tool_2": row["tool_names"][1],
                "count": row["count"],
            }
            for row in partition["top_pairs"]
        )
        ordering_rows.extend(partition["ordering_results"])
        locality_rows.extend(partition["locality"])

    _write_csv(table_dir / "top-tool-frequency.csv", top_tool_rows)
    _write_csv(table_dir / "top-pairs.csv", pair_rows)
    _write_csv(table_dir / "ordering-results.csv", ordering_rows)
    _write_csv(table_dir / "workload-locality.csv", locality_rows)
