from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Any

from tatm.io import write_json


def _percent(value: float) -> str:
    return f"{100 * value:.2f}%"


def _table(headers: list[str], rows: list[list[Any]]) -> str:
    def cell(value: Any) -> str:
        return str(value).replace("|", "\\|").replace("\n", " ")

    lines = [
        "| " + " | ".join(cell(header) for header in headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(cell(value) for value in row) + " |")
    return "\n".join(lines)


def _write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    fieldnames = list(rows[0])
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=fieldnames,
            lineterminator="\n",
        )
        writer.writeheader()
        writer.writerows(rows)


def write_dataset_inventory(
    path: Path,
    metadata: dict[str, Any],
    summary: dict[str, Any],
) -> None:
    inventory = summary["inventory"]
    token_dist = inventory["schema_token_distribution"]
    issue_rows = [
        [issue, count]
        for issue, count in inventory["schema_issue_counts"].items()
    ]
    source_rows = [
        [source, count] for source, count in inventory["tool_sources"].items()
    ]
    source_token_rows = [
        [
            source,
            values["median"],
            values["p95"],
            values["max"],
            values["mean"],
        ]
        for source, values in inventory[
            "source_schema_token_distribution"
        ].items()
    ]
    domain_rows = [
        [domain, count]
        for domain, count in list(inventory["top_tool_domains"].items())[:15]
    ]
    longest_rows = [
        [
            row["name"],
            row["source"],
            row["domain"],
            row["schema_tokens"],
        ]
        for row in inventory["longest_tools"][:10]
    ]
    text = f"""# Dataset inventory and schema report

## Scope

This report is generated by `scripts/run_pipeline.py`. It normalizes all public
ToolRet corpus shards and queries plus a static BFCL V4 subset: simple Python,
multiple, parallel, parallel-multiple, and irrelevance.

Public sources:

- [ToolRet paper](https://arxiv.org/abs/2503.01763),
  [tool corpus](https://huggingface.co/datasets/mangopy/ToolRet-Tools), and
  [query corpus](https://huggingface.co/datasets/mangopy/ToolRet-Queries);
- [BFCL repository and format documentation](https://github.com/ShishirPatil/gorilla/tree/main/berkeley-function-call-leaderboard).

ToolRet labels are relevance judgments. BFCL `function` arrays are the tools
exposed to a task, not necessarily the gold functions called. Neither source is
a chronological production trace.

## Inventory

{_table(
    ["Dataset", "Canonical tools", "Tasks", "Evidence"],
    [
        [
            "ToolRet",
            metadata["toolret"]["tools"],
            metadata["toolret"]["tasks"],
            "gold relevance",
        ],
        [
            "BFCL subset",
            metadata["bfcl"]["tools"],
            metadata["bfcl"]["tasks"],
            "exposed menu",
        ],
        [
            "Combined",
            metadata["combined"]["tools"],
            metadata["combined"]["tasks"],
            "mixed; analyzed separately",
        ],
    ],
)}

ToolRet has {metadata["toolret"]["missing_label_references"]} label references
that do not resolve to the downloaded corpus and
{metadata["toolret"]["empty_label_tasks"]} tasks with no parsed labels.

## Canonical serialization

Each normalized tool is serialized deterministically as:

```json
{{"function":{{"description":"...","name":"...","parameters":{{...}}}},"type":"function"}}
```

Object keys are sorted, whitespace is removed, UTF-8 text is preserved, and
parameter dictionaries are normalized to JSON Schema object form. Counts use
`{summary["tokenizer"]}` without a chat-template wrapper.

## Tool sources

{_table(["Source", "Tools"], source_rows)}

## Canonical schema-token length

{_table(
    ["Count", "Min", "Median", "P90", "P95", "P99", "Max", "Mean"],
    [[
        token_dist["count"],
        token_dist["min"],
        token_dist["median"],
        token_dist["p90"],
        token_dist["p95"],
        token_dist["p99"],
        token_dist["max"],
        token_dist["mean"],
    ]],
)}

### Length by source

{_table(
    ["Source", "Median", "P95", "Max", "Mean"],
    source_token_rows,
)}

### Ten longest canonical schemas

{_table(
    ["Tool", "Source", "Domain", "Schema tokens"],
    longest_rows,
)}

## Schema-quality flags

Flags are descriptive normalization diagnostics, not proof that a benchmark
record is unusable. For example, a no-argument function legitimately has an
empty parameter object.

{_table(["Issue", "Tools"], issue_rows)}

Tools with at least one flag: {inventory["tools_with_any_issue"]} of
{inventory["tools"]}.

## Largest inferred domains

{_table(["Domain", "Tools"], domain_rows)}

## Format observations

- ToolRet corpus files are Parquet with `id` and a heterogeneous JSON-encoded
  `documentation` field. Query Parquet files contain `id`, query/instruction
  text, JSON-encoded relevance `labels`, and category metadata.
- BFCL files use JSON Lines despite the `.json` extension. Each task contains a
  conversation-like `question` and one or more inline function definitions.
- ToolRet code tools often use non-OpenAI fields such as `functionality`,
  `api_call`, `api_arguments`, and `example_code`; the normalizer records
  missing fields instead of silently inventing rich schemas.
- BFCL function definitions are merged by canonical schema hash so repeated
  identical definitions share an identity.

## Limitations

Token counts exclude model-specific chat-template wrappers and separators, so
cluster requests must re-tokenize the complete rendered prompt. Public benchmark
frequency must not be presented as production popularity. BFCL menu exposure
must not be presented as successful-call frequency.
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def write_access_patterns(path: Path, summary: dict[str, Any]) -> None:
    sections: list[str] = [
        "# Tool-access, replay, and trie analysis",
        "",
        "This report keeps ToolRet gold relevance and BFCL menu exposure in "
        "separate partitions. Ordered adjacency is only an order proxy; neither "
        "dataset provides a natural production execution trace.",
    ]
    for partition_name, partition in summary["partitions"].items():
        tool_count = partition["task_tool_count"]
        token_count = partition["task_schema_tokens"]
        top_tool_rows = [
            [
                row["name"],
                row["occurrences"],
                row["schema_tokens"],
                row["weighted_tokens"],
            ]
            for row in partition["top_tools"][:10]
        ]
        empirical_rows = [
            [
                row["ordering"],
                row["trie_nodes"],
                _percent(row["node_compression_ratio"]),
                row["cacheable_block_tokens"],
                _percent(row["estimated_block_reuse_ratio"]),
            ]
            for row in partition["ordering_results"]
            if row["replay"] == "empirical"
        ]
        locality_rows = [
            [
                row["replay"],
                _percent(row["same_domain_ratio"]),
                _percent(row["shared_tool_ratio"]),
                f'{row["mean_tool_jaccard"]:.4f}',
            ]
            for row in partition["locality"]
        ]
        # One ordering is enough to show the locality effect; sweeping every
        # ordering across every capacity would bury it in rows.
        capacity_rows = [
            [
                _percent(row["capacity_fraction"]),
                row["replay"],
                _percent(row["estimated_block_reuse_ratio"]),
                f'{row["evictions"]:,}',
            ]
            for row in partition["capacity_results"]
            if row["ordering"] == "frequency"
        ]
        pair_rows = [
            [
                " + ".join(row["tool_names"]),
                row["count"],
            ]
            for row in partition["top_pairs"][:10]
        ]
        triple_rows = [
            [
                " + ".join(row["tool_names"]),
                row["count"],
            ]
            for row in partition["top_triples"][:10]
        ]
        adjacency_rows = [
            [
                f'{row["tool_names"][0]} → {row["tool_names"][1]}',
                row["count"],
                _percent(row["p_next_given_current"]),
            ]
            for row in partition["top_ordered_adjacency_proxy"][:10]
        ]
        replay_best_rows: list[list[Any]] = []
        for replay in ("empirical", "uniform", "skewed", "session_bursty"):
            candidates = [
                row
                for row in partition["ordering_results"]
                if row["replay"] == replay
            ]
            best = max(
                candidates,
                key=lambda row: (
                    row["estimated_block_reuse_ratio"],
                    row["node_compression_ratio"],
                ),
                default=None,
            )
            if best:
                replay_best_rows.append(
                    [
                        replay,
                        best["ordering"],
                        _percent(best["estimated_block_reuse_ratio"]),
                        _percent(best["node_compression_ratio"]),
                    ]
                )

        sections.extend(
            [
                "",
                f"## {partition_name}",
                "",
                _table(
                    [
                        "Tasks",
                        "Unique observed tools",
                        "Tools/task median",
                        "Tools/task P95",
                        "Schema tokens/task median",
                        "Schema tokens/task P95",
                    ],
                    [[
                        partition["tasks"],
                        partition["unique_observed_tools"],
                        tool_count["median"],
                        tool_count["p95"],
                        token_count["median"],
                        token_count["p95"],
                    ]],
                ),
                "",
                "### Highest benchmark support",
                "",
                _table(
                    ["Tool", "Occurrences", "Schema tokens", "Weighted tokens"],
                    top_tool_rows,
                ),
                "",
                "### Co-occurrence and ordered-adjacency proxies",
                "",
                "Co-occurrence is an unordered same-task statistic. Adjacency "
                "uses dataset label/menu order and is not a measured execution "
                "transition.",
                "",
                _table(["Top pair", "Tasks"], pair_rows),
                "",
                _table(["Top triple", "Tasks"], triple_rows),
                "",
                _table(
                    ["Ordered adjacency", "Count", "P(next | current)"],
                    adjacency_rows,
                ),
                "",
                "### Empirical-order trie comparison",
                "",
                _table(
                    [
                        "Ordering",
                        "Trie nodes",
                        "Node compression",
                        "Block-cacheable tokens",
                        "Estimated token reuse",
                    ],
                    empirical_rows,
                ),
                "",
                "FP-tree-style global ordering is descending global support, so "
                "it is intentionally identical to the frequency baseline in this "
                "first implementation. Future conditional FP-tree mining should "
                "be evaluated as a distinct extension.",
                "",
                "### Replay locality",
                "",
                _table(
                    [
                        "Replay",
                        "Same-domain adjacency",
                        "Shared-tool adjacency",
                        "Mean tool Jaccard",
                    ],
                    locality_rows,
                ),
                "",
                "### Best ordering per replay (analytical estimate)",
                "",
                _table(
                    [
                        "Replay",
                        "Ordering",
                        "Estimated token reuse",
                        "Node compression",
                    ],
                    replay_best_rows,
                ),
                "",
                "The three tables above assume unbounded retention. Under that "
                "assumption trie reuse depends only on the multiset of requests "
                "and not on their order, so `session_bursty` — a permutation of "
                "`empirical` — is identical to it **by construction**, and the "
                "`uniform`/`skewed` differences come from resampling with "
                "replacement rather than from locality. Request order can only "
                "matter once capacity forces eviction, so the locality question "
                "is answered by the next table, not by these.",
                "",
                "### Reuse under a finite cache (frequency ordering)",
                "",
                "Capacity is a fraction of this partition's distinct-tool token "
                f'working set ({partition["working_set_tokens"]:,} tokens), '
                "evicted leaf-first by least-recently-used.",
                "",
                _table(
                    [
                        "Capacity",
                        "Replay",
                        "Estimated token reuse",
                        "Evictions",
                    ],
                    capacity_rows,
                ),
                "",
                f"Pair/triple calculations skipped "
                f'{partition["cooccurrence_tasks_skipped_over_25_tools"]["pairs"]}'
                " tasks with more than 25 exposed tools to avoid combinatorial "
                "distortion.",
            ]
        )

    sections.extend(
        [
            "",
            "## Interpretation boundary",
            "",
            "The cache result is an analytical tool-unit trie estimate. It rounds "
            "shared canonical tool tokens down to 16-token blocks. It excludes "
            "constant system/user prefixes, chat-template separators, GPU "
            "pressure, and scheduler effects, and it counts reuse at tool "
            "boundaries while real block boundaries fall wherever the rendered "
            "prompt puts them — so it is an upper bound, not a prediction. The "
            "finite-cache tables model eviction; the unbounded tables do not. "
            "Measured vLLM cache hits are required before any latency claim.",
            "",
            "A useful positive signal is ordering-dependent block reuse on "
            "multi-tool workloads, especially under bursty replay. A negative or "
            "flat ToolRet result is also expected when most relevance sets contain "
            "one tool; reordering cannot improve a one-item sequence.",
            "",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(sections), encoding="utf-8")


def load_probe_results(results_dir: Path) -> dict[str, Any] | None:
    """Load the Task B probe outputs if they have been produced on a GPU.

    Reports are generated by the pipeline, so measured results should normally
    be read back here rather than hand-written into markdown. If cluster-only
    raw files are absent, ``write_initial_findings`` preserves the already
    committed measured section while regenerating the surrounding analysis.
    """
    def read(name: str) -> dict[str, Any] | None:
        path = results_dir / name
        if not path.exists():
            return None
        return json.loads(path.read_text(encoding="utf-8"))

    enabled = read("cache-enabled.json")
    if enabled is not None and enabled.get("format_version", 1) < 2:
        enabled = None  # single-trial format has no intervals; treat as absent

    validations = [
        json.loads(path.read_text(encoding="utf-8"))
        for path in sorted(results_dir.glob("validate-*.json"))
    ]
    quality_06b = {
        "alphabetical": read("bfcl-quality-alphabetical-score.json"),
        "frequency": read("bfcl-quality-frequency-score.json"),
    }
    quality_8b = {
        "alphabetical": read("bfcl-quality-alphabetical-8b-score.json"),
        "frequency": read("bfcl-quality-frequency-8b-score.json"),
    }
    locality_replays = [
        json.loads(path.read_text(encoding="utf-8"))
        for path in sorted(results_dir.glob("locality-replay-*.json"))
    ]
    bundle = {
        "enabled": enabled,
        "disabled": read("cache-disabled.json"),
        "sweep_enabled": read("prefill-sweep-enabled.json"),
        "sweep_disabled": read("prefill-sweep-disabled.json"),
        "validations": validations,
        "quality_06b": quality_06b if any(quality_06b.values()) else None,
        "quality_8b": quality_8b if any(quality_8b.values()) else None,
        "locality_replays": locality_replays,
    }
    return bundle if any(bundle.values()) else None


_PROBE_SCENARIOS = (
    ("original_cold", "Cold prompt"),
    ("original_identical", "Identical prompt reuse"),
    ("changed_second_tool", "Changed second tool"),
    ("reordered_first_two", "Reordered first two tools"),
    ("original_restored", "Original restored"),
)


def _sweep_section(probe: dict[str, Any] | None) -> str:
    """Where prefix caching starts to pay, measured against a control."""
    if probe is None or probe.get("sweep_enabled") is None:
        return ""
    enabled = probe["sweep_enabled"]
    disabled = probe.get("sweep_disabled")
    off_by_size = {}
    if disabled is not None:
        off_by_size = {row["menu_tools"]: row for row in disabled["results"]}

    rows = []
    crossover = None
    for row in enabled["results"]:
        warm = row["warm_ttft_seconds"]["mean"]
        cold = row["cold_ttft_seconds"]["mean"]
        off_row = off_by_size.get(row["menu_tools"])
        off_warm = off_row["warm_ttft_seconds"]["mean"] if off_row else None
        speedup = f"{off_warm / warm:.1f}x" if off_warm and warm else "—"
        if off_warm and off_warm / warm >= 1.2 and crossover is None:
            crossover = row["menu_tools"]
        rows.append(
            [
                row["menu_tools"],
                f'{row["prompt_tokens"]:,}',
                f"{cold * 1000:.1f}",
                f"{warm * 1000:.1f}",
                f"{off_warm * 1000:.1f}" if off_warm else "—",
                speedup,
            ]
        )

    crossover_text = (
        f"Prefix caching first produces a material gain at **{crossover} tools** "
        "and grows steeply from there."
        if crossover
        else "No menu size showed a material cache-on/cache-off gap."
    )
    return "\n".join(
        [
            "## Prefill cost and the measurement floor",
            "",
            "Menus are one gold tool padded with distractors from a fixed global "
            "catalog. Cold is measured after a prefix-cache reset; warm is an "
            f'identical repeat. {enabled["repeats"]} trials per point.',
            "",
            _table(
                [
                    "Menu tools",
                    "Prompt tokens",
                    "Cold TTFT on (ms)",
                    "Warm TTFT on (ms)",
                    "Warm TTFT off (ms)",
                    "Speedup",
                ],
                rows,
            ),
            "",
            crossover_text,
            "",
            "The cache-disabled control shows cold and warm within noise of each "
            "other at every size, so the gap above is prefix caching and not a "
            "warmup artifact. Note that within-run cold-vs-warm separation alone "
            "is not sufficient evidence: the control also 'separates' at one tool, "
            "where no cache exists. The cache-on/cache-off comparison is the "
            "trustworthy one.",
            "",
            "This supersedes the earlier reading that prefix reuse buys nothing. "
            "It buys nothing *at 303 tokens*, which is simply below the floor.",
            "",
        ]
    )


def _validation_section(probe: dict[str, Any] | None) -> str:
    """Analytical trie estimate versus what vLLM actually cached."""
    if probe is None or not probe.get("validations"):
        return ""
    rows = []
    for run in probe["validations"]:
        predicted = run["predicted"]
        measured = run["measured"]
        rows.append(
            [
                run["run_label"].replace("validate-", ""),
                f'{predicted["cacheable_block_tokens"]:,}',
                f'{measured["cached_prompt_tokens"]:,.0f}',
                f'{run["measured_over_predicted_ratio"]:.2f}x'
                if run.get("measured_over_predicted_ratio")
                else "—",
                _percent(predicted["estimated_block_reuse_ratio"]),
                _percent(measured["measured_reuse_ratio"]),
            ]
        )
    return "\n".join(
        [
            "## Analytical estimate versus measured cache hits",
            "",
            _table(
                [
                    "Workload",
                    "Predicted cacheable",
                    "Measured cached",
                    "Measured/predicted",
                    "Predicted reuse",
                    "Measured reuse",
                ],
                rows,
            ),
            "",
            "The tool-unit model under-predicts rather than over-predicts. It "
            "ignores the chat template and system preamble, which are identical "
            "across requests and are themselves cached, and that outweighs the "
            "partial blocks it loses at tool boundaries.",
            "",
            "The ordering comparison inverts the gold-only recommendation. On "
            "padded menus, ordering by benchmark support puts the *task-specific* "
            "tools first and pushes the shared catalog behind them, destroying the "
            "common prefix. A stable global order that ignores task-specificity "
            "keeps the shared catalog in front. Frequency ordering is the right "
            "choice only when the whole menu is task-specific, which is not what a "
            "connected tool catalog looks like.",
            "",
        ]
    )


def _quality_section(probe: dict[str, Any] | None) -> str:
    """Function-call quality under ordering, at whichever model sizes were run."""
    if probe is None:
        return ""
    quality_06b = probe.get("quality_06b")
    quality_8b = probe.get("quality_8b")
    if not quality_06b and not quality_8b:
        return ""

    def rows_for(bundle: dict[str, Any] | None) -> list[list[Any]]:
        rows = []
        for ordering in ("alphabetical", "frequency"):
            score = (bundle or {}).get(ordering)
            if score is None:
                continue
            overall = score["overall"]
            rows.append(
                [
                    ordering,
                    _percent(overall["function_name_accuracy"] or 0),
                    _percent(overall["full_accuracy"] or 0),
                    _percent(overall["no_tool_accuracy"] or 0),
                ]
            )
        return rows

    sections = [
        "## Does the winning ordering preserve function-call quality?",
        "",
        "100 BFCL tasks (20 per category, 64-tool menus), scored against BFCL "
        "`possible_answer` ground truth. Alphabetical is the ordering measured "
        "strongest for cache reuse; frequency is the comparison Task D's "
        "analytical model originally recommended.",
        "",
    ]
    rows_06b = rows_for(quality_06b)
    if rows_06b:
        sections.extend(
            [
                "`Qwen/Qwen3-0.6B`:",
                "",
                _table(
                    [
                        "Ordering",
                        "Function-name accuracy",
                        "Full accuracy",
                        "No-tool accuracy",
                    ],
                    rows_06b,
                ),
                "",
            ]
        )
    rows_8b = rows_for(quality_8b)
    if rows_8b:
        sections.extend(
            [
                "`Qwen/Qwen3-8B`, identical workload:",
                "",
                _table(
                    [
                        "Ordering",
                        "Function-name accuracy",
                        "Full accuracy",
                        "No-tool accuracy",
                    ],
                    rows_8b,
                ),
                "",
            ]
        )
    if rows_06b and rows_8b:
        sections.append(
            "The name/full-accuracy gap that looked real at 0.6B is not present "
            "at 8B — both orderings score identically there. Checking a "
            "counterintuitive small-model result against a second model size "
            "found that most of the apparent quality tradeoff was a small-model "
            "artefact; only a smaller no-tool-accuracy gap favouring alphabetical "
            "survives at both scales. One run per condition, no repeats; read as "
            "directional rather than final."
        )
    else:
        sections.append(
            "One run per condition, no repeats or confidence intervals, and only "
            "two of six orderings scored; read as directional rather than final."
        )
    sections.append("")
    return "\n".join(sections)


def _locality_replay_section(probe: dict[str, Any] | None) -> str:
    """Whether request order changes reuse under real GPU cache eviction."""
    if probe is None or not probe.get("locality_replays"):
        return ""
    rows = []
    note = None
    has_legacy = False
    for run in probe["locality_replays"]:
        legacy = int(run.get("format_version", 1)) < 2
        has_legacy |= legacy
        capacity = run.get("cache_capacity_tokens")
        for name, condition in run.get("conditions", {}).items():
            predicted = condition.get("predicted", {})
            volume = condition.get("total_prompt_tokens", 0)
            volume_type = (
                "canonical tool tokens" if legacy else "rendered prompt tokens"
            )
            rows.append(
                [
                    name,
                    f"{volume:,}",
                    volume_type,
                    f'{condition.get("measured_cached_tokens", 0):,.0f}',
                    _percent(condition["measured_reuse_ratio"]),
                    _percent(predicted.get("estimated_block_reuse_ratio", 0)),
                    f'{predicted.get("evictions", 0):,}',
                ]
            )
        if note is None and capacity:
            total = next(iter(run.get("conditions", {}).values()), {}).get(
                "total_prompt_tokens", 0
            )
            note = (
                f"Recorded {volume_type} volume ({total:,}) versus nominal "
                "cache capacity "
                f"({capacity:,} tokens) for this run."
            )
    if not rows:
        return ""
    return "\n".join(
        [
            "## Does request order matter on the live GPU cache?",
            "",
            "Every other GPU experiment above resets the prefix cache before each "
            "trial, which is repeatable but erases the cross-request dependency "
            "locality is actually about. This instead runs one continuous session "
            "per replay condition — a single reset, then every request in "
            "sequence — comparing `empirical` against `session_bursty`, the one "
            "replay pair that is a strict permutation of the same task multiset.",
            "",
            _table(
                [
                    "Replay",
                    "Recorded token volume",
                    "Volume type",
                    "Measured cached tokens",
                    "Cached / recorded volume",
                    "Predicted reuse (bounded trie)",
                    "Predicted evictions",
                ],
                rows,
            ),
            "",
            note or "",
            "",
            (
                "Legacy format-v1 runs mislabeled canonical tool-token volume "
                "as full prompt tokens, so their displayed cached/volume value "
                "is not a standard rendered-prompt cache-hit ratio. Their "
                "measured cached-token totals remain usable for a matched "
                "between-order comparison, but they did not sample occupancy "
                "and cannot directly prove eviction. Re-run with format v2 for "
                "the corrected denominator and measured pressure."
                if has_legacy
                else "Format-v2 runs use rendered prompt tokens, reconcile them "
                "with the engine query counter, and include sampled KV occupancy. "
                "Only runs that reached their predeclared pressure threshold "
                "should support an eviction-pressure claim."
            ),
            "",
        ]
    )


def _probe_section(probe: dict[str, Any] | None) -> str:
    if probe is None or probe.get("enabled") is None:
        return (
            "## Prefix-cache sanity status\n\n"
            "Not yet measured. Run `scripts/vllm_prefix_cache_probe.py` on a "
            "CUDA GPU as described in `cluster/README.md`; no synthetic number "
            "is substituted here.\n"
        )

    enabled = probe["enabled"]
    disabled = probe.get("disabled")
    config = enabled.get("server_cache_config", {})
    rows = []
    for key, label in _PROBE_SCENARIOS:
        summary_row = enabled["summary"][key]
        cached = summary_row["cached_prompt_tokens"]["mean"]
        prompt_tokens = summary_row["prompt_tokens"]
        ttft = summary_row["ttft_seconds"]
        cell = f'{ttft["mean"] * 1000:.1f} ± {ttft.get("ci95_half_width", 0) * 1000:.1f}'
        off_cell = "—"
        if disabled is not None:
            off = disabled["summary"][key]["ttft_seconds"]
            off_cell = (
                f'{off["mean"] * 1000:.1f} ± '
                f'{off.get("ci95_half_width", 0) * 1000:.1f}'
            )
        rows.append(
            [
                label,
                f'{cached:.0f} / {"/".join(str(v) for v in prompt_tokens)}',
                _percent(summary_row["reuse_fraction"]),
                cell,
                off_cell,
            ]
        )

    control_note = (
        "No cache-disabled control has been run, so output equality is "
        "unverified."
    )
    if disabled is not None:
        control_flag = disabled.get("server_cache_config", {}).get(
            "enable_prefix_caching"
        )
        max_cached = max(
            row["cached_prompt_tokens"]["max"]
            for row in disabled["summary"].values()
        )
        if control_flag is False and max_cached == 0:
            control_note = (
                "The control served `enable_prefix_caching=False` and reported "
                "0 cached tokens in every scenario, so the cache-on/cache-off "
                "output comparison is meaningful."
            )
        else:
            control_note = (
                "**The control is invalid**: it served "
                f"`enable_prefix_caching={control_flag}` and reported up to "
                f"{max_cached:.0f} cached tokens. Omitting "
                "`--enable-prefix-caching` does not disable the feature in "
                "vLLM V1; restart with `--no-enable-prefix-caching`."
            )

    return "\n".join(
        [
            "## Prefix-cache sanity results",
            "",
            f'Measured on {enabled["model"]}, block size '
            f'{config.get("block_size")}, {config.get("num_gpu_blocks")} GPU '
            f'blocks, {enabled["repeats"]} trials per scenario with the prefix '
            "cache reset before each trial. Intervals are 95% Student-t "
            "half-widths.",
            "",
            _table(
                [
                    "Check",
                    "Cached / prompt tokens",
                    "Reuse",
                    "TTFT on (ms)",
                    "TTFT off (ms)",
                ],
                rows,
            ),
            "",
            control_note,
            "",
        ]
    )


def write_initial_findings(
    path: Path,
    summary: dict[str, Any],
    probe: dict[str, Any] | None = None,
) -> None:
    token_dist = summary["inventory"]["schema_token_distribution"]
    toolret = summary["partitions"]["toolret_gold"]
    bfcl = summary["partitions"]["bfcl_exposed"]

    def empirical(partition: dict[str, Any], ordering: str) -> dict[str, Any]:
        return next(
            row
            for row in partition["ordering_results"]
            if row["replay"] == "empirical" and row["ordering"] == ordering
        )

    tr_original = empirical(toolret, "original")
    tr_weighted = empirical(toolret, "schema_cost_weighted")
    bf_original = empirical(bfcl, "original")
    bf_frequency = empirical(bfcl, "frequency")
    tr_gain = (
        tr_weighted["estimated_block_reuse_ratio"]
        - tr_original["estimated_block_reuse_ratio"]
    )
    bf_gain = (
        bf_frequency["estimated_block_reuse_ratio"]
        - bf_original["estimated_block_reuse_ratio"]
    )
    prefix_section = ""
    if probe is None or probe.get("enabled") is None:
        # Raw GPU replays are intentionally git-ignored and may exist only on
        # the cluster. A CPU-only regeneration must not erase a previously
        # committed measured section merely because those raw files are absent
        # on this machine. Preserve only the generated GPU block; the dataset
        # analysis and recommendation below are still regenerated normally.
        if path.exists():
            existing = path.read_text(encoding="utf-8")
            start = existing.find("## Prefix-cache sanity results")
            end = existing.find("## Recommendation", start)
            if start >= 0 and end > start:
                prefix_section = existing[start:end].strip()
    if not prefix_section:
        prefix_section = "\n".join(
            section
            for section in (
                _probe_section(probe),
                _sweep_section(probe),
                _validation_section(probe),
                _quality_section(probe),
                _locality_replay_section(probe),
            )
            if section
        )
    flagged = summary["inventory"]["tools_with_any_issue"]
    total_tools = summary["inventory"]["tools"]

    text = f"""# Initial research findings and recommendation

## Result in one paragraph

The public workloads contain a measurable analytical prefix-locality signal,
but it is workload- and evidence-dependent. Across {total_tools:,} canonical
tools, median schema length is {token_dist["median"]:.0f} Qwen tokens and P95 is
{token_dist["p95"]:.0f}. ToolRet's median relevance set and BFCL's median
exposed menu both contain one tool, which limits what reordering can achieve on
many tasks. On empirical dataset order, schema-cost-weighted ordering raises the
ToolRet tool-prefix block-reuse estimate from
{_percent(tr_original["estimated_block_reuse_ratio"])} to
{_percent(tr_weighted["estimated_block_reuse_ratio"])} ({100 * tr_gain:.2f}
percentage points). Frequency ordering raises the BFCL menu estimate from
{_percent(bf_original["estimated_block_reuse_ratio"])} to
{_percent(bf_frequency["estimated_block_reuse_ratio"])} ({100 * bf_gain:.2f}
points). These are analytical estimates, not vLLM hit-rate or latency results.

## Evidence obtained locally

- ToolRet: {toolret["tasks"]:,} tasks, {toolret["unique_observed_tools"]:,}
  tools appearing in gold relevance labels, with every label resolved.
- BFCL subset: {bfcl["tasks"]:,} tasks and
  {bfcl["unique_observed_tools"]:,} distinct canonical functions appearing in
  exposed menus.
- Schema diagnostics flag {flagged:,}/{total_tools:,} tools. Most flags are
  empty parameter objects, which can be legitimate; malformed and missing-field
  counts are reported separately.
- Controlled support-skewed replay produces much more reuse than uniform or
  empirical access, but under unbounded retention that gap comes from
  resampling with replacement — repeated requests — not from locality. Only the
  finite-cache tables in `access-patterns.md` speak to request ordering.
- Classic FP-tree global order equals the frequency order in this baseline.
  Conditional pattern mining is still untested.

{prefix_section}

## Recommendation

Measured evidence now supports alphabetical ordering over the frequency
ordering this analysis originally recommended: on padded, deployment-realistic
menus, alphabetical measures 38.15% cache reuse versus frequency's 4.41%, and
a follow-up quality check found this does not cost function-selection accuracy
at deployment-grade model scale (identical on `Qwen3-8B`), with only a smaller
no-tool-accuracy gap surviving at both model sizes checked. Continue the exact
prompt-level ToolTrie baseline with alphabetical as the default ordering,
reporting the original order and fixed-random controls alongside it.

The likely publishable refinement is not a generic "reorder context into a
trie" claim, because closely related cache-aware context ordering already
exists. Before selecting an extension, the initial brief still requires the
retrieval and systems measurements listed below. The later Phase 2 comparison
in `reports/tooltrie-phase2/findings.md` supersedes this report's pilot-quality
interpretation and must be cited for ToolTrie/ContextPilot quality claims.

Do not pursue arbitrary independent KV concatenation yet. Native exact APC
already converts the local token-reuse signal into a repeatable TTFT benefit
(10.6x at 200 tools). Phase 2 subsequently detected a no-tool regression for
reuse-optimizing orders, so this report must not describe the optimization as
quality-preserving without that qualification. The open questions are coverage
and safe use, not whether the cache mechanism works at all.

## What remains before the extensions in the brief

The missing harnesses are now implemented, but their GPU outputs are not folded
into this generated report yet. A 200-query lexical retrieval curve is saved in
`reports/retrieval-bm25-sweep.json`; it must remain separate from cache and call
quality results.

1. Replay `build_retrieved_tool_workload.py` outputs at the declared menu sizes,
   reporting retrieval recall/MRR separately from ordering, cache, and call
   quality.
2. Run `audit_rendered_prefix.py --measure` to store the exact server-rendered
   token IDs, block boundaries, actual cached tokens, prefill, and TTFT for the
   same partial-reuse requests.
3. Repeat live-cache measurements across the six brief orderings and all four
   workload regimes. `replay_vllm_workload.py` and `locality_replay.py` now
   report direct partial-reuse buckets and sampled KV occupancy; a pressure run
   must declare and reach its occupancy threshold.
4. Replay the now-predeclared `ordinary_text_prefill_fallback` condition. The
   harness requires original retrieval-rank order and records that no inactive
   tools are retained and no KV tensors are modified. GPU measurements remain
   pending; this path is the default whenever expected prefill savings do not
   exceed context, decode, or safety cost.
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def write_reports(
    report_dir: Path,
    metadata: dict[str, Any],
    summary: dict[str, Any],
    results_dir: Path | None = None,
) -> None:
    report_dir.mkdir(parents=True, exist_ok=True)
    write_json(report_dir / "analysis-summary.json", summary)
    write_dataset_inventory(
        report_dir / "dataset-inventory.md",
        metadata,
        summary,
    )
    write_access_patterns(report_dir / "access-patterns.md", summary)
    probe = load_probe_results(results_dir) if results_dir is not None else None
    write_initial_findings(report_dir / "initial-findings.md", summary, probe)

    table_dir = report_dir / "tables"
    issue_rows = [
        {"issue": issue, "tools": count}
        for issue, count in summary["inventory"]["schema_issue_counts"].items()
    ]
    _write_csv(table_dir / "schema-issues.csv", issue_rows)

    top_tool_rows: list[dict[str, Any]] = []
    pair_rows: list[dict[str, Any]] = []
    ordering_rows: list[dict[str, Any]] = []
    locality_rows: list[dict[str, Any]] = []
    for partition_name, partition in summary["partitions"].items():
        top_tool_rows.extend(
            {"partition": partition_name, **row}
            for row in partition["top_tools"]
        )
        pair_rows.extend(
            {
                "partition": partition_name,
                "tool_1": row["tool_names"][0],
                "tool_2": row["tool_names"][1],
                "count": row["count"],
            }
            for row in partition["top_pairs"]
        )
        ordering_rows.extend(partition["ordering_results"])
        locality_rows.extend(partition["locality"])

    _write_csv(table_dir / "top-tool-frequency.csv", top_tool_rows)
    _write_csv(table_dir / "top-pairs.csv", pair_rows)
    _write_csv(table_dir / "ordering-results.csv", ordering_rows)
    _write_csv(table_dir / "workload-locality.csv", locality_rows)
