from __future__ import annotations

import csv
from pathlib import Path
from typing import Any

from tatm.io import write_json


def _percent(value: float) -> str:
    return f"{100 * value:.2f}%"


def _table(headers: list[str], rows: list[list[Any]]) -> str:
    def cell(value: Any) -> str:
        return str(value).replace("|", "\\|").replace("\n", " ")

    lines = [
        "| " + " | ".join(cell(header) for header in headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(cell(value) for value in row) + " |")
    return "\n".join(lines)


def _write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    fieldnames = list(rows[0])
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=fieldnames,
            lineterminator="\n",
        )
        writer.writeheader()
        writer.writerows(rows)


def write_dataset_inventory(
    path: Path,
    metadata: dict[str, Any],
    summary: dict[str, Any],
) -> None:
    inventory = summary["inventory"]
    token_dist = inventory["schema_token_distribution"]
    issue_rows = [
        [issue, count]
        for issue, count in inventory["schema_issue_counts"].items()
    ]
    source_rows = [
        [source, count] for source, count in inventory["tool_sources"].items()
    ]
    source_token_rows = [
        [
            source,
            values["median"],
            values["p95"],
            values["max"],
            values["mean"],
        ]
        for source, values in inventory[
            "source_schema_token_distribution"
        ].items()
    ]
    domain_rows = [
        [domain, count]
        for domain, count in list(inventory["top_tool_domains"].items())[:15]
    ]
    longest_rows = [
        [
            row["name"],
            row["source"],
            row["domain"],
            row["schema_tokens"],
        ]
        for row in inventory["longest_tools"][:10]
    ]
    text = f"""# Dataset inventory and schema report

## Scope

This report is generated by `scripts/run_pipeline.py`. It normalizes all public
ToolRet corpus shards and queries plus a static BFCL V4 subset: simple Python,
multiple, parallel, parallel-multiple, and irrelevance.

Public sources:

- [ToolRet paper](https://arxiv.org/abs/2503.01763),
  [tool corpus](https://huggingface.co/datasets/mangopy/ToolRet-Tools), and
  [query corpus](https://huggingface.co/datasets/mangopy/ToolRet-Queries);
- [BFCL repository and format documentation](https://github.com/ShishirPatil/gorilla/tree/main/berkeley-function-call-leaderboard).

ToolRet labels are relevance judgments. BFCL `function` arrays are the tools
exposed to a task, not necessarily the gold functions called. Neither source is
a chronological production trace.

## Inventory

{_table(
    ["Dataset", "Canonical tools", "Tasks", "Evidence"],
    [
        [
            "ToolRet",
            metadata["toolret"]["tools"],
            metadata["toolret"]["tasks"],
            "gold relevance",
        ],
        [
            "BFCL subset",
            metadata["bfcl"]["tools"],
            metadata["bfcl"]["tasks"],
            "exposed menu",
        ],
        [
            "Combined",
            metadata["combined"]["tools"],
            metadata["combined"]["tasks"],
            "mixed; analyzed separately",
        ],
    ],
)}

ToolRet has {metadata["toolret"]["missing_label_references"]} label references
that do not resolve to the downloaded corpus and
{metadata["toolret"]["empty_label_tasks"]} tasks with no parsed labels.

## Canonical serialization

Each normalized tool is serialized deterministically as:

```json
{{"function":{{"description":"...","name":"...","parameters":{{...}}}},"type":"function"}}
```

Object keys are sorted, whitespace is removed, UTF-8 text is preserved, and
parameter dictionaries are normalized to JSON Schema object form. Counts use
`{summary["tokenizer"]}` without a chat-template wrapper.

## Tool sources

{_table(["Source", "Tools"], source_rows)}

## Canonical schema-token length

{_table(
    ["Count", "Min", "Median", "P90", "P95", "P99", "Max", "Mean"],
    [[
        token_dist["count"],
        token_dist["min"],
        token_dist["median"],
        token_dist["p90"],
        token_dist["p95"],
        token_dist["p99"],
        token_dist["max"],
        token_dist["mean"],
    ]],
)}

### Length by source

{_table(
    ["Source", "Median", "P95", "Max", "Mean"],
    source_token_rows,
)}

### Ten longest canonical schemas

{_table(
    ["Tool", "Source", "Domain", "Schema tokens"],
    longest_rows,
)}

## Schema-quality flags

Flags are descriptive normalization diagnostics, not proof that a benchmark
record is unusable. For example, a no-argument function legitimately has an
empty parameter object.

{_table(["Issue", "Tools"], issue_rows)}

Tools with at least one flag: {inventory["tools_with_any_issue"]} of
{inventory["tools"]}.

## Largest inferred domains

{_table(["Domain", "Tools"], domain_rows)}

## Format observations

- ToolRet corpus files are Parquet with `id` and a heterogeneous JSON-encoded
  `documentation` field. Query Parquet files contain `id`, query/instruction
  text, JSON-encoded relevance `labels`, and category metadata.
- BFCL files use JSON Lines despite the `.json` extension. Each task contains a
  conversation-like `question` and one or more inline function definitions.
- ToolRet code tools often use non-OpenAI fields such as `functionality`,
  `api_call`, `api_arguments`, and `example_code`; the normalizer records
  missing fields instead of silently inventing rich schemas.
- BFCL function definitions are merged by canonical schema hash so repeated
  identical definitions share an identity.

## Limitations

Token counts exclude model-specific chat-template wrappers and separators, so
cluster requests must re-tokenize the complete rendered prompt. Public benchmark
frequency must not be presented as production popularity. BFCL menu exposure
must not be presented as successful-call frequency.
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def write_access_patterns(path: Path, summary: dict[str, Any]) -> None:
    sections: list[str] = [
        "# Tool-access, replay, and trie analysis",
        "",
        "This report keeps ToolRet gold relevance and BFCL menu exposure in "
        "separate partitions. Ordered adjacency is only an order proxy; neither "
        "dataset provides a natural production execution trace.",
    ]
    for partition_name, partition in summary["partitions"].items():
        tool_count = partition["task_tool_count"]
        token_count = partition["task_schema_tokens"]
        top_tool_rows = [
            [
                row["name"],
                row["occurrences"],
                row["schema_tokens"],
                row["weighted_tokens"],
            ]
            for row in partition["top_tools"][:10]
        ]
        empirical_rows = [
            [
                row["ordering"],
                row["trie_nodes"],
                _percent(row["node_compression_ratio"]),
                row["cacheable_block_tokens"],
                _percent(row["estimated_block_reuse_ratio"]),
            ]
            for row in partition["ordering_results"]
            if row["replay"] == "empirical"
        ]
        locality_rows = [
            [
                row["replay"],
                _percent(row["same_domain_ratio"]),
                _percent(row["shared_tool_ratio"]),
                f'{row["mean_tool_jaccard"]:.4f}',
            ]
            for row in partition["locality"]
        ]
        pair_rows = [
            [
                " + ".join(row["tool_names"]),
                row["count"],
            ]
            for row in partition["top_pairs"][:10]
        ]
        triple_rows = [
            [
                " + ".join(row["tool_names"]),
                row["count"],
            ]
            for row in partition["top_triples"][:10]
        ]
        adjacency_rows = [
            [
                f'{row["tool_names"][0]} → {row["tool_names"][1]}',
                row["count"],
                _percent(row["p_next_given_current"]),
            ]
            for row in partition["top_ordered_adjacency_proxy"][:10]
        ]
        replay_best_rows: list[list[Any]] = []
        for replay in ("empirical", "uniform", "skewed", "session_bursty"):
            candidates = [
                row
                for row in partition["ordering_results"]
                if row["replay"] == replay
            ]
            best = max(
                candidates,
                key=lambda row: (
                    row["estimated_block_reuse_ratio"],
                    row["node_compression_ratio"],
                ),
                default=None,
            )
            if best:
                replay_best_rows.append(
                    [
                        replay,
                        best["ordering"],
                        _percent(best["estimated_block_reuse_ratio"]),
                        _percent(best["node_compression_ratio"]),
                    ]
                )

        sections.extend(
            [
                "",
                f"## {partition_name}",
                "",
                _table(
                    [
                        "Tasks",
                        "Unique observed tools",
                        "Tools/task median",
                        "Tools/task P95",
                        "Schema tokens/task median",
                        "Schema tokens/task P95",
                    ],
                    [[
                        partition["tasks"],
                        partition["unique_observed_tools"],
                        tool_count["median"],
                        tool_count["p95"],
                        token_count["median"],
                        token_count["p95"],
                    ]],
                ),
                "",
                "### Highest benchmark support",
                "",
                _table(
                    ["Tool", "Occurrences", "Schema tokens", "Weighted tokens"],
                    top_tool_rows,
                ),
                "",
                "### Co-occurrence and ordered-adjacency proxies",
                "",
                "Co-occurrence is an unordered same-task statistic. Adjacency "
                "uses dataset label/menu order and is not a measured execution "
                "transition.",
                "",
                _table(["Top pair", "Tasks"], pair_rows),
                "",
                _table(["Top triple", "Tasks"], triple_rows),
                "",
                _table(
                    ["Ordered adjacency", "Count", "P(next | current)"],
                    adjacency_rows,
                ),
                "",
                "### Empirical-order trie comparison",
                "",
                _table(
                    [
                        "Ordering",
                        "Trie nodes",
                        "Node compression",
                        "Block-cacheable tokens",
                        "Estimated token reuse",
                    ],
                    empirical_rows,
                ),
                "",
                "FP-tree-style global ordering is descending global support, so "
                "it is intentionally identical to the frequency baseline in this "
                "first implementation. Future conditional FP-tree mining should "
                "be evaluated as a distinct extension.",
                "",
                "### Replay locality",
                "",
                _table(
                    [
                        "Replay",
                        "Same-domain adjacency",
                        "Shared-tool adjacency",
                        "Mean tool Jaccard",
                    ],
                    locality_rows,
                ),
                "",
                "### Best ordering per replay (analytical estimate)",
                "",
                _table(
                    [
                        "Replay",
                        "Ordering",
                        "Estimated token reuse",
                        "Node compression",
                    ],
                    replay_best_rows,
                ),
                "",
                f"Pair/triple calculations skipped "
                f'{partition["cooccurrence_tasks_skipped_over_25_tools"]["pairs"]}'
                " tasks with more than 25 exposed tools to avoid combinatorial "
                "distortion.",
            ]
        )

    sections.extend(
        [
            "",
            "## Interpretation boundary",
            "",
            "The cache result is an analytical tool-unit trie estimate. It rounds "
            "shared canonical tool tokens down to 16-token blocks and assumes an "
            "unbounded retained trie. It excludes constant system/user prefixes, "
            "chat-template separators, eviction, GPU pressure, and scheduler "
            "effects. The CUDA vLLM probe in `cluster/` is required before making "
            "latency or cache-hit claims.",
            "",
            "A useful positive signal is ordering-dependent block reuse on "
            "multi-tool workloads, especially under bursty replay. A negative or "
            "flat ToolRet result is also expected when most relevance sets contain "
            "one tool; reordering cannot improve a one-item sequence.",
            "",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(sections), encoding="utf-8")


def write_initial_findings(path: Path, summary: dict[str, Any]) -> None:
    token_dist = summary["inventory"]["schema_token_distribution"]
    toolret = summary["partitions"]["toolret_gold"]
    bfcl = summary["partitions"]["bfcl_exposed"]

    def empirical(partition: dict[str, Any], ordering: str) -> dict[str, Any]:
        return next(
            row
            for row in partition["ordering_results"]
            if row["replay"] == "empirical" and row["ordering"] == ordering
        )

    tr_original = empirical(toolret, "original")
    tr_weighted = empirical(toolret, "schema_cost_weighted")
    bf_original = empirical(bfcl, "original")
    bf_frequency = empirical(bfcl, "frequency")
    tr_gain = (
        tr_weighted["estimated_block_reuse_ratio"]
        - tr_original["estimated_block_reuse_ratio"]
    )
    bf_gain = (
        bf_frequency["estimated_block_reuse_ratio"]
        - bf_original["estimated_block_reuse_ratio"]
    )
    flagged = summary["inventory"]["tools_with_any_issue"]
    total_tools = summary["inventory"]["tools"]

    text = f"""# Initial research findings and recommendation

## Result in one paragraph

The public workloads contain a measurable analytical prefix-locality signal,
but it is workload- and evidence-dependent. Across {total_tools:,} canonical
tools, median schema length is {token_dist["median"]:.0f} Qwen tokens and P95 is
{token_dist["p95"]:.0f}. ToolRet's median relevance set and BFCL's median
exposed menu both contain one tool, which limits what reordering can achieve on
many tasks. On empirical dataset order, schema-cost-weighted ordering raises the
ToolRet tool-prefix block-reuse estimate from
{_percent(tr_original["estimated_block_reuse_ratio"])} to
{_percent(tr_weighted["estimated_block_reuse_ratio"])} ({100 * tr_gain:.2f}
percentage points). Frequency ordering raises the BFCL menu estimate from
{_percent(bf_original["estimated_block_reuse_ratio"])} to
{_percent(bf_frequency["estimated_block_reuse_ratio"])} ({100 * bf_gain:.2f}
points). These are analytical estimates, not vLLM hit-rate or latency results.

## Evidence obtained locally

- ToolRet: {toolret["tasks"]:,} tasks, {toolret["unique_observed_tools"]:,}
  tools appearing in gold relevance labels, with every label resolved.
- BFCL subset: {bfcl["tasks"]:,} tasks and
  {bfcl["unique_observed_tools"]:,} distinct canonical functions appearing in
  exposed menus.
- Schema diagnostics flag {flagged:,}/{total_tools:,} tools. Most flags are
  empty parameter objects, which can be legitimate; malformed and missing-field
  counts are reported separately.
- Controlled support-skewed replay produces much more reuse than uniform or
  empirical access, confirming that any systems claim must state its workload
  locality rather than assume production-like skew.
- Classic FP-tree global order equals the frequency order in this baseline.
  Conditional pattern mining is still untested.

## Prefix-cache sanity status

| Check | Local status | Required cluster evidence |
| --- | --- | --- |
| Identical prompt reuse | Pending CUDA vLLM | cached/computed prompt tokens and TTFT |
| Changed second tool | Pending CUDA vLLM | first differing block boundary |
| Reordered tools | Pending CUDA vLLM | rendered token IDs and hit boundary |
| Cache on/off equivalence | Pending CUDA vLLM | identical generated token sequence |
| GPU/KV memory | Unavailable on this Mac | GPU type, cache usage, eviction settings |

The runnable probe and procedure are in `cluster/README.md`; no synthetic GPU
number is substituted here.

## Recommendation

Proceed with the exact prompt-level ToolTrie baseline on the cluster, focusing
on multi-tool tasks and session-local replay. Use schema-cost-weighted ordering
as the strongest ToolRet candidate and frequency ordering as the strongest BFCL
candidate from this first analysis. Report the original order and fixed-random
controls alongside them.

The likely publishable refinement is not a generic “reorder context into a
trie” claim, because closely related cache-aware context ordering already
exists. The more defensible direction is tool-specific cache admission using
schema cost plus workflow co-occurrence, while preserving an active/authorized
tool manifest and measuring function-call quality.

Do not pursue arbitrary independent KV concatenation yet. First establish that
native exact APC converts the local token-reuse signal into repeatable TTFT
benefit without a BFCL quality regression. If it does not, narrow the project to
characterizing the crossover regimes or pivot toward retrieval/menu reduction.

## Immediate cluster run

1. Freeze model revision, tokenizer, chat template, vLLM version, GPU, block
   size, dtype, and server flags.
2. Run the cache-enabled and cache-disabled sanity probe.
3. Render and save complete prompt token IDs for each ordering.
4. Replay original, frequency, and schema-cost-weighted workloads with
   documented cold/warm policies and repeated trials.
5. Add BFCL name/argument/no-tool scores before interpreting latency.
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def write_reports(
    report_dir: Path,
    metadata: dict[str, Any],
    summary: dict[str, Any],
) -> None:
    report_dir.mkdir(parents=True, exist_ok=True)
    write_json(report_dir / "analysis-summary.json", summary)
    write_dataset_inventory(
        report_dir / "dataset-inventory.md",
        metadata,
        summary,
    )
    write_access_patterns(report_dir / "access-patterns.md", summary)
    write_initial_findings(report_dir / "initial-findings.md", summary)

    table_dir = report_dir / "tables"
    issue_rows = [
        {"issue": issue, "tools": count}
        for issue, count in summary["inventory"]["schema_issue_counts"].items()
    ]
    _write_csv(table_dir / "schema-issues.csv", issue_rows)

    top_tool_rows: list[dict[str, Any]] = []
    pair_rows: list[dict[str, Any]] = []
    ordering_rows: list[dict[str, Any]] = []
    locality_rows: list[dict[str, Any]] = []
    for partition_name, partition in summary["partitions"].items():
        top_tool_rows.extend(
            {"partition": partition_name, **row}
            for row in partition["top_tools"]
        )
        pair_rows.extend(
            {
                "partition": partition_name,
                "tool_1": row["tool_names"][0],
                "tool_2": row["tool_names"][1],
                "count": row["count"],
            }
            for row in partition["top_pairs"]
        )
        ordering_rows.extend(partition["ordering_results"])
        locality_rows.extend(partition["locality"])

    _write_csv(table_dir / "top-tool-frequency.csv", top_tool_rows)
    _write_csv(table_dir / "top-pairs.csv", pair_rows)
    _write_csv(table_dir / "ordering-results.csv", ordering_rows)
    _write_csv(table_dir / "workload-locality.csv", locality_rows)
